---
title: Jesus Calls
timezone: GMT
destination: _site/
domainname: https://jesuscallsministries.org
baseurl: /
sitename: Jesus Calls
assetsurl: /static-assets/
markdown: kramdown
highlighter: rouge
exclude:
  - config
  - screenshots
  - node_modules
  - gulpfile.js
  - package.json
  - src
  - README.md
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-entrypoint.sh
port: 4000
plugins:
  - liquid-md5
sass:
  style: :compressed
# webmentions = true/false
# bootstrap = true/false
webmentions: true
bootstrap: false
